---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 4/11/2026 2:54 PM
---

local RedArmyBases = {}

--- Blueprints
RedArmyBases.towns = {
    -- 6 spawners, laser-gun defense
    "0eNqdmuFu2zAMhN9Fv51CkiVZyqsMxeBkWmcgcQrb2VYUefclLbAEQy7k7c+wDfVXkzqfKIrvZrM71tdpGBezfjfD9jDOZv3l3czDy9jvLv839vtq1ublOK6W4zTVxZwaM4zf6m+zdqfmzo/Oy2Gsq1/9bnfzo/703Jg6LsMy1M9f8fGPt6/jcb+p05nV3Hm+Ma+H+fzIYbzwz5iVC0+xMW+Xv8WneLq8wD8grwRFCdQqQa0ECkqQl0BRCXISKClBVgJ1OlCROFnHyRKn6DidxHFWB0oiSKlrUdZOqWtR1k6na/mFdLKW30enajnTOlHLS6/TtChFp9O0+Gk4nablb9XrNC27h9dpWvYzr9O07LBep2nF5qETtbx5+EhvQy0gJZoUAOmq7Jvt/O4ea/+S7F3SVdu7fq7TA5YXWUX5VlYitVZHyiKINm2wdq1nQWDp2lab8CQGF0j/R7FFkoNCS8rQ5Mh0+paXP6s4CkEWZWjyVxJ02pY/3eBYhwPrFjwLAkIKLW1wDpACTfKAFNUGd824BxnXClyB6tico/gyC0IpL2zKCzjbWHrtLCA5epuz99MdPfvRIVDLphvFxtYnKNt0edIBEF2dZACii5MMcn2Vdj/Pdb/ZDePLat9vfwzn13OPDnEoxkISJWBizRyEmlgvB7lPrJWjuGgnR/0J2sgTAP2HjyeQbN7GEYl1cRQca+Io24XtvYGSoKM9HIEc23tDIPaEiTisgSNOIA+qiHOr680jTwMbSZceA8TnO1IzKJBMSgZxCtlkBZxsSeUhjuOEhzCe0wvCkPJFGNaWgXFltvpAXeNEuzuw5HyVc93V7TIN29X34zT22/rg40LhZQImsQq764AIi+UkgBrsZMkBwirsLQ2oXApbcYDKpQSy+gQVWYlcZYcwicsyioosNFCSWY9Gp5fCHhYLup2x5HKhg5mzjlswDCJraBgaadUo186yZo16Bc6ydo2aBc7yho1aIc52rDNiFFlI4/gKCUIpd2wljbp0TnsBeSW1iOTZjw60IJ1r6esDzArk9QEmRe76AIMS1/XHGe9IEBRBZq8PcHCFavvD2JS3kWJoN5eRuusDGJn31PUB5rTc9QEGBfb6AKPIugSDyMoErz9Zm2ABZPIkiics2PIEj1hY8jSKSWwnBJM8OfSDSS05h4RJgZv7waDIDSJhUOIGfzCo40aRMCiTmwAEFW6CCA/+kNYNOY6aIMIcT03+YE5LTSJhTqAmfzAnUpNImJO4wR8M6rhRJAzKXHcMgwo3ioSH0Mj2CAY5rmP3CXpuzLDU/fmh60BuY37Waf54JCZfQikxh9Sd/zid/gBbQeAI"
}
--- Max length of the town
RedArmyBases.towns_length = 48
RedArmyBases.towns_size = #RedArmyBases.towns

RedArmyBases.artillery_towns = {
}
RedArmyBases.artillery_towns_length = 48
RedArmyBases.artillery_towns_size = #RedArmyBases.artillery_towns

RedArmyBases.artillery_cities = {
    
}
RedArmyBases.artillery_cities_length = 64
RedArmyBases.artillery_cities_size = #RedArmyBases.artillery_cities

RedArmyBases.nuclear_cities = {
    
}
RedArmyBases.nuclear_cities_cities = 64
RedArmyBases.nuclear_cities_size = #RedArmyBases.nuclear_cities


return RedArmyBases