---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 10/29/2024 2:29 AM
---
require("__erm_redarmy__/global")

local MapGenFunctions = require('__erm_libs__/prototypes/map_gen')
-- Update RTS world
local mapgen = data.raw["map-gen-presets"]["default"]
mapgen["erm-rts-death-world"]["basic_settings"]["autoplace_controls"][AUTOCONTROL_NAME] = { frequency = "very-high", size = "very-big" }

if mapgen["death-world"] then
    mapgen["death-world"]["basic_settings"]["autoplace_controls"][AUTOCONTROL_NAME] = { frequency = "very-high", size = "very-big" }
end

if mapgen["erm-debug"] then
    mapgen["erm-debug"]["basic_settings"]["autoplace_controls"][AUTOCONTROL_NAME] = { frequency = 5, size = 5 }
end

local nauvis_autocontrols = data.raw.planet.nauvis.map_gen_settings.autoplace_controls
local nauvis_enemy_settings = settings.startup["enemyracemanager-nauvis-enemy"].value
if nauvis_enemy_settings == MOD_NAME then
    MapGenFunctions.remove_enemy_autoplace_controls(nauvis_autocontrols)
    nauvis_autocontrols[AUTOCONTROL_NAME] = {}
elseif nauvis_enemy_settings == NAUVIS_MIXED then
    nauvis_autocontrols[AUTOCONTROL_NAME] = {}
end