---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/22/2020 7:15 PM
---

-- Globals within the mod
MOD_NAME = 'erm_redarmy'
FORCE_NAME = 'enemy_erm_redarmy'

DEBUG_MODE = false

CHARACTER_RIG_STILL_FRAME = 12

DROPSHIP_ATTACK = 'emrmy-dsh'
ENGINEER_ATTACK = 'emrmy-gin'

REDARMY_MAP_COLOR = { r = 220, g = 20, b = 60, a = 255 }