---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/29/2023 11:02 PM
---
require('global')

data:extend {
    --- Startup Tab
    {
        type = "color-setting",
        name = FORCE_NAME.."-map-color",
        description = FORCE_NAME.."-map-color",
        setting_type = "startup",
        default_value = REDARMY_MAP_COLOR,
        order = "erm_redarmy-100"
    },
    {
        type = "int-setting",
        name = FORCE_NAME.."-artillery-refuel",
        description = FORCE_NAME.."-artillery-refuel",
        setting_type = "startup",
        default_value = 6,
        allowed_values = {3,5,6,9,12},
        order = "erm_redarmy-101",
    },
    {
        type = "int-setting",
        name = FORCE_NAME.."-artillery-manual-fire-chance",
        description = FORCE_NAME.."-artillery-manual-fire-chance",
        setting_type = "startup",
        default_value = 25,
        allowed_values = {20,25,33,50,66,75,80},
        order = "erm_redarmy-102",
    },
    {
        type = "int-setting",
        name = FORCE_NAME.."-large-town-spawn-chance",
        description = FORCE_NAME.."-large-town-spawn-chance",
        setting_type = "startup",
        default_value = 50,
        allowed_values = {20,25,33,50,66,75,80},
        order = "erm_redarmy-110",
    },
    {
        type = "int-setting",
        name = FORCE_NAME.."-artillery-town-spawn-chance",
        description = FORCE_NAME.."-artillery-town-spawn-chance",
        setting_type = "startup",
        default_value = 33,
        allowed_values = {20,25,33,50,66,75,80},
        order = "erm_redarmy-111",
    },
    {
        type = "int-setting",
        name = FORCE_NAME.."-artillery-city-spawn-chance",
        description = FORCE_NAME.."-artillery-city-spawn-chance",
        setting_type = "startup",
        default_value = 50,
        allowed_values = {20,25,33,50,66,75,80},
        order = "erm_redarmy-112",
    },
    {
        type = "int-setting",
        name = FORCE_NAME.."-atomic-rocket-refuel",
        description = FORCE_NAME.."-atomic-rocket-refuel",
        setting_type = "startup",
        default_value = 6,
        allowed_values = {1,2,3,5,6,9,12},
        order = "erm_redarmy-120",
    },
    {
        type = "int-setting",
        name = FORCE_NAME.."-atomic-city-spawn-chance",
        description = FORCE_NAME.."-atomic-city-spawn-chance",
        setting_type = "startup",
        default_value = 50,
        allowed_values = {20,25,33,50,66,75,80},
        order = "erm_redarmy-121",
    },
    {
        type = "bool-setting",
        name = FORCE_NAME.."-orbital-surveillance",
        description = FORCE_NAME.."-orbital-surveillance",
        setting_type = "startup",
        default_value = true,
        order = "erm_redarmy-130",
    },
}