---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/29/2023 11:02 PM
---
require('global')

data:extend {
    --- Startup Tab
    {
        type = "color-setting",
        name = "erm_redarmy-map-color",
        description = "erm_redarmy-map-color",
        setting_type = "startup",
        default_value = REDARMY_MAP_COLOR,
        order = "erm_redarmy-100"
    },
}