---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/2/2024 7:01 PM
---

local simulations = require("__erm_redarmy__/prototypes/tips_and_tricks/simulations")
local ERM_REDARMY = require('__erm_redarmy__/global')

data:extend(
        {
            {
                type = "tips-and-tricks-item-category",
                name = ERM_REDARMY.FORCE_NAME,
                order = "n02-["..ERM_REDARMY.FORCE_NAME.."]"
            },
            {
                type = "tips-and-tricks-item",
                name = ERM_REDARMY.FORCE_NAME.."-general-info",
                tag = "[entity="..ERM_REDARMY.FORCE_NAME.."--human-flamethrower--1]",
                category = ERM_REDARMY.FORCE_NAME,
                order = "a",
                is_title = true,
                starting_status = "suggested",
                simulation = simulations.general
            },
        }
)

if mods['space-age'] then
    data:extend(
            {
                {
                    type = "tips-and-tricks-item",
                    tag = "[planet=earth]",
                    name = ERM_REDARMY.FORCE_NAME.."-planet-earth",
                    category = ERM_REDARMY.FORCE_NAME,
                    order = "c",
                    indent = 1,
                    starting_status = "suggested",
                    simulation = simulations.planet_earth
                },
                {
                    type = "tips-and-tricks-item",
                    tag = "[item=enemy_erm_redarmy--organ]",
                    name = ERM_REDARMY.FORCE_NAME.."-economy",
                    category = ERM_REDARMY.FORCE_NAME,
                    order = "c",
                    indent = 1,
                    starting_status = "suggested",
                    image = "__erm_redarmy__/graphics/economy/erm-redarmy.png"
                },
                {
                    type = "tips-and-tricks-item",
                    name = ERM_REDARMY.FORCE_NAME.."-city-and-town",
                    category = ERM_REDARMY.FORCE_NAME,
                    order = "d",
                    indent = 2,
                    starting_status = "suggested",
                    simulation = simulations.city_town
                },
                {
                    type = "tips-and-tricks-item",
                    tag = "[item=rocket-silo]",
                    name = ERM_REDARMY.FORCE_NAME.."-rocket-silo",
                    category = ERM_REDARMY.FORCE_NAME,
                    order = "e",
                    indent = 2,
                    starting_status = "suggested",
                    simulation = simulations.rocket_silo
                },
                {
                    type = "tips-and-tricks-item",
                    name = ERM_REDARMY.FORCE_NAME.."-boss-rocket-silo",
                    category = ERM_REDARMY.FORCE_NAME,
                    order = "e1",
                    indent = 3,
                    starting_status = "suggested",
                    simulation = simulations.rocket_silo
                },
                {
                    type = "tips-and-tricks-item",
                    tag = "[item=artillery-turret]",
                    name = ERM_REDARMY.FORCE_NAME.."-artillery-turret",
                    category = ERM_REDARMY.FORCE_NAME,
                    order = "f",
                    indent = 2,
                    starting_status = "suggested",
                    simulation = simulations.artillery
                },
            })
end