---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/2/2024 7:01 PM
---
---
local simulations = {}

simulations.general = {
    init = [[
require("__core__/lualib/story")
local sim = game.simulation
sim.camera_position = {0, 0}
sim.camera_zoom = 0.85
sim.hide_cursor = true
player = sim.create_test_player{name = "you"}
sim.camera_player = player
game.planets["earth"].create_surface()
local earth_surface = game.surfaces["earth"]
earth_surface.request_to_generate_chunks({0,0}, 2)
earth_surface.force_generate_chunk_requests()


local tank
local story_table =
{
    {
        {
            name = "start",
            init = function()
                local entities = earth_surface.find_entities {{-64, -64}, {64, 64}}
                for _, ent in pairs(entities) do
                    ent.destroy()
                end
                player.teleport({-3,10},earth_surface)
                tank = earth_surface.create_entity { name="tank", position={0, 10}, force="player" }
                earth_surface.create_entity { name="enemy_erm_redarmy--human-flamethrower--5", position={8, -2} }
                earth_surface.create_entity { name="enemy_erm_redarmy--tank-explosive-cannon--5", position={8, 2} }
                earth_surface.create_entity { name="enemy_erm_redarmy--plane-gunner--5", position={8, 0} }
                earth_surface.create_entity { name="enemy_erm_redarmy--human-machinegun--5", position={8, 4} }
            end
        },
        {
            condition = story_elapsed_check(3),
            action = function()
                tank.die()
            end
        },
        {
            condition = story_elapsed_check(3),
            action = function()
                story_jump_to(storage.story, "start")
            end
        }
    }
}
tip_story_init(story_table)
    ]],
}



simulations.planet_earth = {
    init = [[
require("__core__/lualib/story")

game.planets["earth"].create_surface()
local earth_surface = game.surfaces["earth"]
earth_surface.request_to_generate_chunks({0,0}, 2)
earth_surface.force_generate_chunk_requests()

local sim = game.simulation
player = sim.create_test_player{name = "you"}
sim.camera_player = player
sim.camera_position = {0, 0}
sim.camera_zoom = 0.5
sim.hide_cursor = true

local story_table =
{
    {
        {
            name = "start",
            init = function()
                local entities = earth_surface.find_entities {{-64, -64}, {64, 64}}
                for _, ent in pairs(entities) do
                    ent.destroy()
                end

                earth_surface.create_entity { name="cargo-landing-pad", position={-25, -10}, force="player" }
                player.teleport({-22,0}, "earth")
                for _, y in pairs({-5,0,5}) do
                    for _, x in pairs({-20, -17}) do
                        local gun = earth_surface.create_entity { name="gun-turret", position={x, y}, force="player" }
                        local inventory = gun.get_inventory(defines.inventory.turret_ammo)
                        inventory.insert({name = "piercing-rounds-magazine", count = 100})
                    end
                end

                for i = -10, 10, 1 do
                    earth_surface.create_entity { name="stone-wall", position={-15, i}, force="player" }
                end

                earth_surface.create_entity { name="enemy_erm_redarmy--lab--5", position={12, -5} }
                earth_surface.create_entity { name="enemy_erm_redarmy--assemble-machine--5", position={12, 5} }
                earth_surface.create_entity { name="enemy_erm_redarmy--electric-furnace--5", position={16, 0} }
            end,
        },
        {
            condition = story_elapsed_check(2),
            action = function()
                earth_surface.create_entity { name="enemy_erm_redarmy--human-machinegun--5", position={8, 2} }
                earth_surface.create_entity { name="enemy_erm_redarmy--human-sniper--5", position={8, 0} }
                earth_surface.create_entity { name="enemy_erm_redarmy--human-flamethrower--5", position={8, 4} }
            end
        },
        {
            condition = story_elapsed_check(2),
            action = function()
                earth_surface.create_entity { name="enemy_erm_redarmy--tank-cannon--5", position={8, 2} }
                earth_surface.create_entity { name="enemy_erm_redarmy--plane-gunner--5", position={8, 0} }
                earth_surface.create_entity { name="enemy_erm_redarmy--plane-bomber--5", position={8, 4} }
            end
        },
        {
            condition = story_elapsed_check(10),
            action = function()
                story_jump_to(storage.story, "start")
            end
        }
    }
}
tip_story_init(story_table)
]]
}

simulations.city_town = {
    init = [[
require("__core__/lualib/story")

game.planets["earth"].create_surface()
local earth_surface = game.surfaces["earth"]
earth_surface.request_to_generate_chunks({0,0}, 2)
earth_surface.force_generate_chunk_requests()

local sim = game.simulation
player = sim.create_test_player{name = "you"}
sim.camera_player = player
sim.camera_position = {0, 0}
sim.camera_zoom = 0.5
sim.hide_cursor = true

local story_table =
{
    {
        {
            name = "start",
            init = function()
                local entities = earth_surface.find_entities {{-64, -64}, {64, 64}}
                for _, ent in pairs(entities) do
                    ent.destroy()
                end

                earth_surface.create_entity { name="cargo-landing-pad", position={-25, -10}, force="player" }
                player.teleport({-22,0}, "earth")
                for _, y in pairs({-5,0,5}) do
                    for _, x in pairs({-20, -17}) do
                        local gun = earth_surface.create_entity { name="gun-turret", position={x, y}, force="player" }
                        local inventory = gun.get_inventory(defines.inventory.turret_ammo)
                        inventory.insert({name = "piercing-rounds-magazine", count = 100})
                    end
                end

                for i = -10, 10, 1 do
                    earth_surface.create_entity { name="stone-wall", position={-15, i}, force="player" }
                end

                for i = -30, 30, 1 do
                    earth_surface.create_entity { name="stone-wall", position={20, i}, force="enemy" }
                end

                earth_surface.create_entity { name="enemy_erm_redarmy--lab--5", position={25, -5} }
                earth_surface.create_entity { name="enemy_erm_redarmy--assemble-machine--5", position={25, 5} }
                earth_surface.create_entity { name="enemy_erm_redarmy--electric-furnace--5", position={25, 0} }
                earth_surface.create_entity { name="enemy_erm_redarmy--artillery-turret--5", position={25, -10} }
                earth_surface.create_entity { name="enemy_erm_redarmy--tesla-turret--5", position={25, -15} }
                earth_surface.create_entity { name="enemy_erm_redarmy--tesla-turret--5", position={25, 15} }
                local rocket_silo = earth_surface.create_entity { name="enemy_erm_redarmy--rocket-silo--5", position={35, -5} }
            end,
        },
        {
            condition = story_elapsed_check(2),
            action = function()
                earth_surface.create_entity { name="enemy_erm_redarmy--human-machinegun--5", position={20, 2} }
                earth_surface.create_entity { name="enemy_erm_redarmy--human-sniper--5", position={20, 0} }
                earth_surface.create_entity { name="enemy_erm_redarmy--human-flamethrower--5", position={20, 4} }
            end
        },
        {
            condition = story_elapsed_check(2),
            action = function()
                earth_surface.create_entity { name="enemy_erm_redarmy--tank-cannon--5", position={20, 2} }
                earth_surface.create_entity { name="enemy_erm_redarmy--plane-gunner--5", position={20, 0} }
                earth_surface.create_entity { name="enemy_erm_redarmy--plane-bomber--5", position={20, 4} }
            end
        },
        {
            condition = story_elapsed_check(10),
            action = function()
                story_jump_to(storage.story, "start")
            end
        }
    }
}
tip_story_init(story_table)
]]
}

simulations.rocket_silo = {
    init = [[
require("__core__/lualib/story")

game.planets["earth"].create_surface()
local earth_surface = game.surfaces["earth"]
earth_surface.request_to_generate_chunks({0,0}, 2)
earth_surface.force_generate_chunk_requests()

local sim = game.simulation
player = sim.create_test_player{name = "you"}
sim.camera_player = player
sim.camera_position = {0, 0}
sim.camera_zoom = 0.5
sim.hide_cursor = true

local story_table =
{
    {
        {
            name = "start",
            init = function()
                local entities = earth_surface.find_entities {{-64, -64}, {64, 64}}
                for _, ent in pairs(entities) do
                    ent.destroy()
                end

                earth_surface.create_entity { name="cargo-landing-pad", position={-25, -10}, force="player" }
                player.teleport({-22,0}, "earth")
                for _, y in pairs({-5,0,5}) do
                    for _, x in pairs({-20, -17}) do
                        local gun = earth_surface.create_entity { name="gun-turret", position={x, y}, force="player" }
                        local inventory = gun.get_inventory(defines.inventory.turret_ammo)
                        inventory.insert({name = "piercing-rounds-magazine", count = 100})
                    end
                end

                for i = -10, 10, 1 do
                    earth_surface.create_entity { name="stone-wall", position={-15, i}, force="player" }
                end

                local rocket_silo = earth_surface.create_entity { name="enemy_erm_redarmy--rocket-silo--5", position={12, -5} }
                rocket_silo.rocket_parts = 100
            end,
        },
        {
            condition = story_elapsed_check(2),
            action = function()
                earth_surface.create_entity { name="enemy_erm_redarmy--human-machinegun--5", position={8, 2} }
                earth_surface.create_entity { name="enemy_erm_redarmy--human-sniper--5", position={8, 0} }
                earth_surface.create_entity { name="enemy_erm_redarmy--human-flamethrower--5", position={8, 4} }
            end
        },
        {
            condition = story_elapsed_check(2),
            action = function()
                earth_surface.create_entity { name="enemy_erm_redarmy--tank-cannon--5", position={8, 2} }
                earth_surface.create_entity { name="enemy_erm_redarmy--plane-gunner--5", position={8, 0} }
                earth_surface.create_entity { name="enemy_erm_redarmy--plane-bomber--5", position={8, 4} }
            end
        },
        {
            condition = story_elapsed_check(10),
            action = function()
                story_jump_to(storage.story, "start")
            end
        }
    }
}
tip_story_init(story_table)
]]
}

simulations.artillery = {
    init = [[
require("__core__/lualib/story")

game.planets["earth"].create_surface()
local earth_surface = game.surfaces["earth"]
earth_surface.request_to_generate_chunks({0,0}, 2)
earth_surface.force_generate_chunk_requests()

local sim = game.simulation
player = sim.create_test_player{name = "you"}
sim.camera_player = player
sim.camera_position = {0, 0}
sim.camera_zoom = 0.5
sim.hide_cursor = true

local story_table =
{
    {
        {
            name = "start",
            init = function()
                local entities = earth_surface.find_entities {{-64, -64}, {64, 64}}
                for _, ent in pairs(entities) do
                    ent.destroy()
                end

                earth_surface.create_entity { name="cargo-landing-pad", position={-25, -10}, force="player" }
                player.teleport({-22,0}, "earth")
                for _, y in pairs({-5,0,5}) do
                    for _, x in pairs({-20, -17}) do
                        local gun = earth_surface.create_entity { name="gun-turret", position={x, y}, force="player" }
                        local inventory = gun.get_inventory(defines.inventory.turret_ammo)
                        inventory.insert({name = "piercing-rounds-magazine", count = 100})
                    end
                end

                for i = -10, 10, 1 do
                    earth_surface.create_entity { name="stone-wall", position={-15, i}, force="player" }
                end

                local active_artillery = earth_surface.create_entity { name="enemy_erm_redarmy--artillery-turret--5", position={12, -5} }
                local ammo_inventory = active_artillery.get_inventory(defines.inventory.artillery_turret_ammo)
                local shell = {name= "artillery-shell", count = 20}
                ammo_inventory.insert(shell)
            end,
        },
        {
            condition = story_elapsed_check(2),
            action = function()
                earth_surface.create_entity { name="enemy_erm_redarmy--human-machinegun--5", position={8, 2} }
                earth_surface.create_entity { name="enemy_erm_redarmy--human-sniper--5", position={8, 0} }
                earth_surface.create_entity { name="enemy_erm_redarmy--human-flamethrower--5", position={8, 4} }
            end
        },
        {
            condition = story_elapsed_check(2),
            action = function()
                earth_surface.create_entity { name="enemy_erm_redarmy--tank-cannon--5", position={8, 2} }
                earth_surface.create_entity { name="enemy_erm_redarmy--plane-gunner--5", position={8, 0} }
                earth_surface.create_entity { name="enemy_erm_redarmy--plane-bomber--5", position={8, 4} }
            end
        },
        {
            condition = story_elapsed_check(10),
            action = function()
                story_jump_to(storage.story, "start")
            end
        }
    }
}
tip_story_init(story_table)
]]
}

return simulations