---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/22/2025 1:31 PM
---
--- Create egg item, tech and recipe
---
local FusionEconomy = require("__erm_libs__/prototypes/fusion_economy_helper")
local space_age_item_sounds = require("__space-age__.prototypes.item_sounds")
local item_sounds = require("__base__.prototypes.item_sounds")
local base_tile_sounds = require("__base__/prototypes/tile/tile-sounds")
local simulations = require("__space-age__.prototypes.factoriopedia-simulations")

local Organs = {}

local function get_secondary_color(color)
    color = util.table.deepcopy(color)
    local limit = (240/255)
    local change_r = 60/255
    local change_g = 32/255
    if color.r + change_r < limit then
        color.r = color.r + change_r
    end
    if color.g + change_g < limit then
        color.g = color.g + change_g
    end
    return color
end

function Organs.init()
    data.extend({
        {
            type = "item-subgroup",
            name = "erm-organs-processes",
            group = "intermediate-products",
            order = "m"
        },
    })
end

function Organs.create_item(name)
    data.extend({
        {
            type = "item",
            name = name,
            icon = "__erm_redarmy__/graphics/organ/part-specimin-1.png",
            pictures = {
                {
                    layers = {
                        { size = 64, filename = "__erm_redarmy__/graphics/organ/part-specimin-1.png", scale = 0.5 },
                        { size = 64, filename = "__erm_redarmy__/graphics/organ/part-specimin-2.png", scale = 0.5 },
                        { size = 64, filename = "__erm_redarmy__/graphics/organ/part-specimin-3.png", scale = 0.5 },
                    }
                }
            },
            fuel_category = "chemical",
            fuel_value = "20MJ",
            subgroup = "agriculture-products",
            order = "x[egg]-a[organ]",
            inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
            pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
            drop_sound = space_age_item_sounds.agriculture_inventory_move,
            stack_size = 100,
            weight = 1 * kg,
            spoil_ticks = 0.5 * hour,
            spoil_result = "spoilage",
        }
    })
end

function Organs.create_organ_duplication_recipe(name, additional_ingredients, color_tint)
    color_tint = util.table.deepcopy(color_tint)
    color_tint.a = 1
    local ingredients = {
        {type = "item", name = name, amount = 2}
    }
    
    if additional_ingredients then
        for _, ind in pairs(additional_ingredients) do
            table.insert(ingredients, ind)
        end            
    end

    data.extend({
        {
             type = "recipe",
             name = name.."-clone",
             icon = "__erm_redarmy__/graphics/organ/part-specimin-1.png",
             category = "organic",
             subgroup = "erm-organs-processes",
             order = "x["..name.."]-a[organs]",
             hide_from_player_crafting = true,
             auto_recycle = false,
             preserve_products_in_machine_output = true,
             energy_required = 10,
             ingredients = ingredients,
             results =
             {
                 {type = "item", name = name, amount = 4}
             },
             result_is_always_fresh = true,
             allow_productivity = true,
             allow_quality = false,
             enabled = false,
             crafting_machine_tint =
             {
                 primary = color_tint,
                 secondary = get_secondary_color(color_tint),
             },
         }
    })
end

function Organs.create_organ_to_nutrients_recipe(name, nutrients_amount, color_tint)
    color_tint = util.table.deepcopy(color_tint)
    color_tint.a = 1
    data.extend({
        {
            type = "recipe",
            name = name.."-to-nutrients",
            icons = {
                {
                    icon = "__erm_redarmy__/graphics/organ/part-specimin-1.png",
                    icon_size = 64,
                    scale = 0.5,
                    shift = {-9,-9}
                },
                {
                    icon = "__space-age__/graphics/icons/nutrients.png",
                    icon_size = 64,
                    scale = 0.5,
                    shift = {9, 9}
                },
            },
            category = "organic",
            subgroup = "erm-organs-processes",
            order = "x["..name.."]-a[organ-nutrients]",
            hide_from_player_crafting = true,
            auto_recycle = false,
            enabled = false,
            energy_required = 2,
            ingredients = {{type = "item", name = name, amount = 1}},
            results = {{type="item", name="nutrients", amount= nutrients_amount}},
            allow_productivity = true,
            allow_quality = false,
            crafting_machine_tint =
            {
                primary = color_tint,
                secondary = get_secondary_color(color_tint),
            },
        }

    })
end

function Organs.create_organ_to_biter_egg_recipe(name, additional_ingredients, color_tint)
    color_tint = util.table.deepcopy(color_tint)
    color_tint.a = 1
    local ingredients = {
        {type = "item", name = name, amount = 1}
    }

    if additional_ingredients then
        for _, ind in pairs(additional_ingredients) do
            table.insert(ingredients, ind)
        end
    end

    data.extend({
    {
        type = "recipe",
        name = name.."-to-biter-egg",
        icons = {
            {
                icon = "__erm_redarmy__/graphics/organ/part-specimin-1.png",
                icon_size = 64,
                scale = 0.5,
                shift = {-9,-9}
            },
            {
                icon = "__space-age__/graphics/icons/biter-egg.png",
                icon_size = 64,
                scale = 0.5,
                shift = {9, 9}
            },
        },
        category = "organic",
        subgroup = "erm-organs-processes",
        order = "x["..name.."]-a[biter-egg]",
        hide_from_player_crafting = true,
        auto_recycle = false,
        enabled = false,
        energy_required = 5,
        ingredients = ingredients,
        results = {{type="item", name="biter-egg", amount=1}},
        allow_productivity = true,
        allow_quality = false,
        crafting_machine_tint =
        {
            primary = color_tint,
            secondary = get_secondary_color(color_tint),
        },
    }})
end

function Organs.create_organ_to_military_recipe(name, color_tint)
    color_tint = util.table.deepcopy(color_tint)
    color_tint.a = 1
    data.extend({
        {
            type = "recipe",
            name = name.."-to-military",
            icons = {
                {
                    icon = "__erm_redarmy__/graphics/organ/part-specimin-1.png",
                    icon_size = 64,
                    scale = 0.5,
                    shift = {-9,-9}
                },
                {
                    icon = "__base__/graphics/icons/military-science-pack.png",
                    icon_size = 64,
                    scale = 0.5,
                    shift = {9, 9}
                },
            },
            category = "chemistry",
            order = "x["..name.."]-a[military]",
            hide_from_player_crafting = true,
            auto_recycle = false,
            enabled = false,
            energy_required = 10,
            ingredients = {
                {type="item", name= name, amount = 2},
                {type="item", name="military-science-pack", amount = 10},
            },
            results = {
                {type = "item", name = "military-science-pack", amount = 11, ignored_by_stats = 10, ignored_by_productivity = 10},
            },
            allow_productivity = true,
            allow_quality = false,
            crafting_machine_tint =
            {
                primary = color_tint,
                secondary = get_secondary_color(color_tint),
            },
        }})
end


function Organs.create_organ_to_promethium_recipe(name)
    FusionEconomy.init()
    data.extend({
        {
            type = "recipe",
            name = name.."-to-promethium",
            icons = {
                {
                    icon = "__erm_redarmy__/graphics/organ/part-specimin-1.png",
                    icon_size = 64,
                    scale = 0.5,
                    shift = {-9,-9}
                },
                {
                    icon = "__space-age__/graphics/icons/promethium-science-pack.png",
                    icon_size = 64,
                    scale = 0.5,
                    shift = {9, 9}
                },
            },
            category = "fusion-assembly",
            order = "x["..name.."]-a[promethium]",
            hide_from_player_crafting = true,
            auto_recycle = false,
            enabled = false,
            energy_required = 10,
            ingredients = {
                {type="item", name= name, amount = 10},
                {type="item", name="promethium-science-pack", amount = 10},
                {type="fluid", name="fusion-plasma", amount = 1}
            },
            results = {
                {type = "item", name = "promethium-science-pack", amount = 12, ignored_by_stats = 10, ignored_by_productivity = 10},
                {type= "fluid", name="fluoroketone-hot", amount= 1, temperature = 180, ignored_by_stats = 1, ignored_by_productivity = 1}
            },
            allow_productivity = true,
            allow_quality = false,
        }})
end

function Organs.create_tech(name)
    data.extend({
        {
            type = "technology",
            name = name.."-processing",
            icon = "__erm_redarmy__/graphics/organ/part-specimin-1.png",
            icon_size = 64,
            effects =
            {
                {
                    type = "unlock-recipe",
                    recipe = name.."-clone"
                },
                {
                    type = "unlock-recipe",
                    recipe = name.."-to-biter-egg"
                },
                {
                    type = "unlock-recipe",
                    recipe = name.."-to-promethium"
                },
                {
                    type = "unlock-recipe",
                    recipe = name.."-to-nutrients",  
                },
            },
            research_trigger =
            {
                type = "build-entity",
                entity = "biochamber"
            }
        }
    })

    if data.raw.technology["military-science-pack"] then
        table.insert(data.raw.technology["military-science-pack"].effects, {
            type = "unlock-recipe",
            recipe = name.."-to-military"
        })
    end
end


return Organs