---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/3/2021 10:29 PM
---

local HumanAnimation = {}

HumanAnimation.get_animation = function()
    return  {
        animations = {
            {
                idle =
                {
                    layers =
                    {
                        character_animations.level1.idle,
                        character_animations.level1.idle_mask,
                        character_animations.level1.idle_shadow
                    }
                },
                idle_with_gun =
                {
                    layers =
                    {
                        character_animations.level1.idle_gun,
                        character_animations.level1.idle_gun_mask,
                        character_animations.level1.idle_gun_shadow
                    }
                },
                mining_with_tool =
                {
                    layers =
                    {
                        character_animations.level1.mining_tool,
                        character_animations.level1.mining_tool_mask,
                        character_animations.level1.mining_tool_shadow
                    }
                },
                running_with_gun =
                {
                    layers =
                    {
                        character_animations.level1.running_gun,
                        character_animations.level1.running_gun_mask,
                        character_animations.level1.running_gun_shadow
                    }
                },
                flipped_shadow_running_with_gun =
                {
                    layers =
                    {
                        character_animations.level1.running_gun_shadow_flipped
                    }
                },
                running =
                {
                    layers =
                    {
                        character_animations.level1.running,
                        character_animations.level1.running_mask,
                        character_animations.level1.running_shadow
                    }
                }
            },
            {
                armors = {"heavy-armor", "modular-armor"},
                idle =
                {
                    layers =
                    {
                        character_animations.level1.idle,
                        character_animations.level1.idle_mask,
                        character_animations.level2addon.idle,
                        character_animations.level2addon.idle_mask,
                        character_animations.level1.idle_shadow,
                        character_animations.level2addon.idle_shadow
                    }
                },
                idle_with_gun =
                {
                    layers =
                    {
                        character_animations.level1.idle_gun,
                        character_animations.level1.idle_gun_mask,
                        character_animations.level2addon.idle_gun,
                        character_animations.level2addon.idle_gun_mask,
                        character_animations.level1.idle_gun_shadow,
                        character_animations.level2addon.idle_gun_shadow
                    }
                },
                mining_with_tool =
                {
                    layers =
                    {
                        character_animations.level1.mining_tool,
                        character_animations.level1.mining_tool_mask,
                        character_animations.level2addon.mining_tool,
                        character_animations.level2addon.mining_tool_mask,
                        character_animations.level1.mining_tool_shadow,
                        character_animations.level2addon.mining_tool_shadow
                    }
                },
                running_with_gun =
                {
                    layers =
                    {
                        character_animations.level1.running_gun,
                        character_animations.level1.running_gun_mask,
                        character_animations.level2addon.running_gun,
                        character_animations.level2addon.running_gun_mask,
                        character_animations.level1.running_gun_shadow,
                        character_animations.level2addon.running_gun_shadow
                    }
                },
                flipped_shadow_running_with_gun =
                {
                    layers =
                    {
                        character_animations.level1.running_gun_shadow_flipped,
                        character_animations.level2addon.running_gun_shadow_flipped
                    }
                },
                running =
                {
                    layers =
                    {
                        character_animations.level1.running,
                        character_animations.level1.running_mask,
                        character_animations.level2addon.running,
                        character_animations.level2addon.running_mask,
                        character_animations.level1.running_shadow,
                        character_animations.level2addon.running_shadow
                    }
                }
            },
            {
                armors = {"power-armor", "power-armor-mk2"},
                idle =
                {
                    layers =
                    {
                        character_animations.level1.idle,
                        character_animations.level1.idle_mask,
                        character_animations.level3addon.idle,
                        character_animations.level3addon.idle_mask,
                        character_animations.level1.idle_shadow,
                        character_animations.level3addon.idle_shadow
                    }
                },
                idle_with_gun =
                {
                    layers =
                    {
                        character_animations.level1.idle_gun,
                        character_animations.level1.idle_gun_mask,
                        character_animations.level3addon.idle_gun,
                        character_animations.level3addon.idle_gun_mask,
                        character_animations.level1.idle_gun_shadow,
                        character_animations.level3addon.idle_gun_shadow
                    }
                },
                mining_with_tool =
                {
                    layers =
                    {
                        character_animations.level1.mining_tool,
                        character_animations.level1.mining_tool_mask,
                        character_animations.level3addon.mining_tool,
                        character_animations.level3addon.mining_tool_mask,
                        character_animations.level1.mining_tool_shadow,
                        character_animations.level3addon.mining_tool_shadow
                    }
                },
                running_with_gun =
                {
                    layers =
                    {
                        character_animations.level1.running_gun,
                        character_animations.level1.running_gun_mask,
                        character_animations.level3addon.running_gun,
                        character_animations.level3addon.running_gun_mask,
                        character_animations.level1.running_gun_shadow,
                        character_animations.level3addon.running_gun_shadow
                    }
                },
                flipped_shadow_running_with_gun =
                {
                    layers =
                    {
                        character_animations.level1.running_gun_shadow_flipped,
                        character_animations.level3addon.running_gun_shadow_flipped
                    }
                },
                running =
                {
                    layers =
                    {
                        character_animations.level1.running,
                        character_animations.level1.running_mask,
                        character_animations.level3addon.running,
                        character_animations.level3addon.running_mask,
                        character_animations.level1.running_shadow,
                        character_animations.level3addon.running_shadow
                    }
                }
            }
        }
    }
end

return HumanAnimation;