---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 4/27/2026 11:02 PM
---

local WeaponRig = require("__enemyracemanager__/lib/rig/weapon")
local DataHelper = require("__enemyracemanager__/lib/rig/data_helper")

--- Regular Projectiles ----
data:extend(
        {
            {
                type = "ammo-category",
                name = "redarmy-damage"
            },
        })

local cannon_projectile = WeaponRig.standardize_cannon_projectile(
        util.table.deepcopy(data.raw['projectile']['cannon-projectile']),
        MOD_NAME..'--cannon-projectile'
)
cannon_projectile['force_condition'] = "not-same"
cannon_projectile['hit_collision_mask'] = { layers = {player = true, train = true,   [DataHelper.getFlyingLayerName()] = true}}

local cannon_explosive_projectile = WeaponRig.standardize_explosive_cannon_projectile(
        util.table.deepcopy(data.raw['projectile']['explosive-cannon-projectile']),
        MOD_NAME..'--explosive-cannon-projectile'
)
cannon_explosive_projectile['force_condition'] = "not-same"
cannon_explosive_projectile['hit_collision_mask'] = { layers = {player = true, train = true,   [DataHelper.getFlyingLayerName()] = true}}

local rocket = WeaponRig.standardize_explosive_rocket_damage(
        util.table.deepcopy(data.raw['projectile']['explosive-rocket']),
        MOD_NAME..'--explosive-rocket',
        3
)
rocket['turn_speed'] = nil
rocket['turning_speed_increases_exponentially_with_projectile_speed'] = false
rocket['smoke'][1]['frequency'] = 1 / 5

rocket['action']['action_delivery']['target_effects'][2] = {
    type = "damage",
    damage = { amount = 3.5, type = "explosion" },
}

data:extend({ cannon_projectile, cannon_explosive_projectile, rocket })

local fire_stream = util.table.deepcopy(data.raw['stream']['flamethrower-fire-stream'])
fire_stream['name'] = MOD_NAME..'--flamethrower-fire-stream'
fire_stream['action'][1]['action_delivery']['target_effects'][1]['sticker'] = MOD_NAME..'--fire-sticker'

local fire_sticker = util.table.deepcopy(data.raw['sticker']['fire-sticker'])
fire_sticker['name'] = MOD_NAME..'--fire-sticker'

data.extend({
    fire_sticker,
    fire_stream,
})

--- Boss Projectiles ----
local explosive_rocket_4 = WeaponRig.standardize_explosive_rocket_damage(
        util.table.deepcopy(data.raw['projectile']['explosive-rocket']),
        MOD_NAME.."--explosive-rocket-4--projectile",
        4
)

--- 300 base damage
explosive_rocket_4["action"]["action_delivery"]["target_effects"][6]['action']['action_delivery']['target_effects'][1] = {
    type = "damage",
    damage = { amount = 200, type = "explosion" }
}
explosive_rocket_4["turn_speed"] = 1
explosive_rocket_4["turning_speed_increases_exponentially_with_projectile_speed"] = false
explosive_rocket_4["smoke"][1]["frequency"] = 1 / 5
explosive_rocket_4["action"]["action_delivery"]["target_effects"][2] = {
    type = "damage",
    damage = { amount = 100, type = "explosion" }
}

local falling_rocket_4 = util.table.deepcopy(explosive_rocket_4)
falling_rocket_4['name'] = MOD_NAME.."--explosive-rocket-4--falling_projectile"

local explosive_rocket_8 = WeaponRig.standardize_explosive_rocket_damage(
        util.table.deepcopy(data.raw['projectile']['explosive-rocket']),
        MOD_NAME.."--explosive-rocket-8--projectile",
        8
)

--- 300 base damage
explosive_rocket_8["action"]["action_delivery"]["target_effects"][6]['action']['action_delivery']['target_effects'][1] = {
    type = "damage",
    damage = { amount = 200, type = "explosion" }
}
explosive_rocket_8["turn_speed"] = 1
explosive_rocket_8["turning_speed_increases_exponentially_with_projectile_speed"] = false
explosive_rocket_8["smoke"][1]["frequency"] = 1 / 5
explosive_rocket_8["action"]["action_delivery"]["target_effects"][2] = {
    type = "damage",
    damage = { amount = 100, type = "explosion" }
}

local falling_rocket_8 = util.table.deepcopy(explosive_rocket_8)
falling_rocket_8['name'] = MOD_NAME.."--explosive-rocket-8--falling_projectile"

local explosive_rocket_he = WeaponRig.standardize_explosive_rocket_damage(
        util.table.deepcopy(data.raw['projectile']['explosive-rocket']),
        MOD_NAME.."--explosive-rocket-he--projectile",
        16
)

--- 300 base damage
explosive_rocket_he["action"]["action_delivery"]["target_effects"][6]['action']['action_delivery']['target_effects'][1] = {
    type = "damage",
    damage = { amount = 500, type = "explosion" }
}
explosive_rocket_he["turn_speed"] = 1
explosive_rocket_he["turning_speed_increases_exponentially_with_projectile_speed"] = false
explosive_rocket_he["smoke"][1]["frequency"] = 1 / 5
explosive_rocket_he["action"]["action_delivery"]["target_effects"][2] = {
    type = "damage",
    damage = { amount = 300, type = "explosion" }
}

local falling_rocket_he = util.table.deepcopy(explosive_rocket_he)
falling_rocket_he['name'] = MOD_NAME.."--explosive-rocket-he--falling_projectile"



local atomic_rocket = util.table.deepcopy(data.raw['projectile']['atomic-rocket'])
atomic_rocket['name'] = MOD_NAME.."--atomic-rocket--falling_projectile"

data:extend({
    explosive_rocket_4,
    falling_rocket_4,
    explosive_rocket_8,
    falling_rocket_8,
    explosive_rocket_he,
    falling_rocket_he,
    atomic_rocket
})