---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/3/2021 11:54 PM
---


require("util")
local biter_ai_settings = require ("__base__.prototypes.entity.biter-ai-settings")
local ERM_UnitHelper = require('__enemyracemanager__/lib/rig/unit_helper')
local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
local ERM_AnimationRig = require('__enemyracemanager__/lib/rig/animation')
local ERM_WeaponRig = require('__enemyracemanager__/lib/rig/weapon')
local ERM_DataHelper = require('__enemyracemanager__/lib/rig/data_helper')
local GlobalConfig = require('__enemyracemanager__/lib/global_config')
local ERM_DebugHelper = require('__enemyracemanager__/lib/debug_helper')

local HumanSound = require('__enemyracemanager_assets__/sound/human_sound')

local name = 'plane-dropship'

local hitpoint = 450
local max_hitpoint_multiplier = settings.startup["enemyracemanager-max-hitpoint-multipliers"].value


-- Handles acid and poison resistance
local base_acid_resistance = 10
local incremental_acid_resistance = 65
-- Handles physical resistance
local base_physical_resistance = 0
local incremental_physical_resistance = 75
-- Handles fire and explosive resistance
local base_fire_resistance = 0
local incremental_fire_resistance = 75
-- Handles laser and electric resistance
local base_electric_resistance = 15
local incremental_electric_resistance = 60
-- Handles cold resistance
local base_cold_resistance = 10
local incremental_cold_resistance = 65

-- Handles physical damages

local base_physical_damage = 4
local incremental_physical_damage = 12

-- Handles Attack Speed

local base_attack_speed = 2700
local incremental_attack_speed = 900

local base_movement_speed = 0.25
local incremental_movement_speed = 0.2

-- Misc settings

local pollution_to_join_attack = 120
local distraction_cooldown = 300



local collision_box = { { -0.9, -1.3 }, { 0.9, 1.3 } }
local selection_box = { { -0.9, -1.3 }, { 0.9, 1.3 } }

function ErmRedArmy.make_dropship_plane(level)
    level = level or 1
    local attack_range = ERM_UnitHelper.get_attack_range(level, 0.5)
    local vision_distance = ERM_UnitHelper.get_vision_distance(attack_range)

    local gunship_animation = {
        layers = {
            {
                filename = "__erm_redarmy__/graphics/plane/Cargo_Plane_Spritesheet_Shadowless.png",
                priority = "high",
                width = 224,
                height = 224,
                frame_count = 1,
                direction_count = 36,
                line_length = 6,
                line_height = 6,
                shift = { 0, 0 },
                max_advance = 1,
                scale = 0.75
            },
            {
                filename = "__erm_redarmy__/graphics/plane/Cargo_Plane_Spritesheet_Shadowless.png",
                priority = "high",
                width = 224,
                height = 224,
                frame_count = 1,
                direction_count = 36,
                line_length = 6,
                line_height = 6,
                shift = { 3, 0 },
                max_advance = 1,
                draw_as_shadow = true,
                scale = 0.75
            }
        }
    }

    data:extend({
        {
            type = "unit",
            name = MOD_NAME .. '--' .. name .. '--' .. level,
            localised_name = { 'entity-name.' .. MOD_NAME .. '--' .. name, GlobalConfig.QUALITY_MAPPING[level] },
            icon = "__erm_redarmy__/graphics/plane/Cargo_Plane_Icon.png",
            icon_size = 32,
            flags = { "placeable-enemy", "placeable-player", "placeable-off-grid", "not-flammable" },
            has_belt_immunity = true,
            max_health = ERM_UnitHelper.get_health(hitpoint, max_hitpoint_multiplier, level),
            order = MOD_NAME .. '--unit--' .. name .. '--' .. level,
            subgroup = "erm-dropship-enemies",
            shooting_cursor_size = 2,
            resistances = {
                { type = "acid", percent = ERM_UnitHelper.get_resistance(base_acid_resistance, incremental_acid_resistance, level) },
                { type = "poison", percent = ERM_UnitHelper.get_resistance(base_acid_resistance, incremental_acid_resistance, level) },
                { type = "physical", percent = ERM_UnitHelper.get_resistance(base_physical_resistance, incremental_physical_resistance, level) },
                { type = "fire", percent = ERM_UnitHelper.get_resistance(base_fire_resistance, incremental_fire_resistance, level) },
                { type = "explosion", percent = ERM_UnitHelper.get_resistance(base_fire_resistance, incremental_fire_resistance, level) },
                { type = "laser", percent = ERM_UnitHelper.get_resistance(base_electric_resistance, incremental_electric_resistance, level) },
                { type = "electric", percent = ERM_UnitHelper.get_resistance(base_electric_resistance, incremental_electric_resistance, level) },
                { type = "cold", percent = ERM_UnitHelper.get_resistance(base_cold_resistance, incremental_cold_resistance, level) }
            },
            map_color = ERM_UnitHelper.format_map_color(settings.startup[FORCE_NAME.."-map-color"].value),
            healing_per_tick = ERM_UnitHelper.get_healing(hitpoint, max_hitpoint_multiplier, level),
            collision_mask = ERM_DataHelper.getFlyingCollisionMask(),
            collision_box = collision_box,
            selection_box = selection_box,
            vision_distance = vision_distance,
            can_open_gate = true,
            movement_speed = ERM_UnitHelper.get_movement_speed(base_movement_speed, incremental_movement_speed, level),
            absorptions_to_join_attack = { pollution = ERM_UnitHelper.get_pollution_attack(pollution_to_join_attack, level)},
            distraction_cooldown = distraction_cooldown,
            ai_settings = biter_ai_settings,
            spawning_time_modifier = 1.5,
            attack_parameters = {
                type = "projectile",
                ammo_category = "redarmy-damage",
                range = attack_range,
                min_attack_distance = attack_range - 4,
                cooldown = ERM_UnitHelper.get_attack_speed(base_attack_speed, incremental_attack_speed, level),
                cooldown_deviation = 0.1,
                warmup = 12,
                ammo_type = {
                    category = "biological",
                    target_type = "direction",
                    action = {
                        type = "direct",
                        action_delivery = {
                            type = 'instant',
                            source_effects = {
                                type = "script",
                                effect_id = DROPSHIP_ATTACK,
                            }
                        }
                    }
                },
                animation = gunship_animation
            },
            distance_per_frame = 1,
            run_animation = gunship_animation,
            render_layer = "wires-above",
            corpse = "erm-medium-remnants",
            dying_explosion = "erm-fire-explosion-air_large-1"
        }
    })
end
