---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 4/11/2026 3:23 PM
---

require('util')

local ERM_UnitHelper = require('__enemyracemanager__/lib/rig/unit_helper')
local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
local GlobalConfig = require('__enemyracemanager__/lib/global_config')

local name = 'artillery-turret'

-- Hitpoints
local hitpoint = 10000
local max_hitpoint_multiplier = settings.startup["enemyracemanager-max-hitpoint-multipliers"].value * 2.5

-- Handles acid resistance
local base_acid_resistance = 20
local incremental_acid_resistance = 30
-- Handles physical resistance
local base_physical_resistance = 30
local incremental_physical_resistance = 20
-- Handles fire and explosive resistance
local base_fire_resistance = 30
local incremental_fire_resistance = 20
-- Handles laser and electric resistance
local base_electric_resistance = 0
local incremental_electric_resistance = 50
-- Handles cold resistance
local base_cold_resistance = 0
local incremental_cold_resistance = 50

-- Handles damages
local base_physical_damage = 0.25
local incremental_physical_damage = 0.75

-- Handles Attack Speed
local base_attack_speed = 200
local incremental_attack_speed = 50

function ErmRedArmy.make_artillery_turret(level)
    level = level or 1

    local attack_range = 512

    local redarmy_artillery_turret = util.table.deepcopy(data.raw['artillery-turret']['artillery-turret'])

    -- Base changes
    redarmy_artillery_turret['subgroup'] = 'enemies'
    redarmy_artillery_turret['name'] = MOD_NAME .. '--' .. name .. '--' .. level
    redarmy_artillery_turret['localised_name'] = { 'entity-name.' .. MOD_NAME .. '--' .. name, GlobalConfig.QUALITY_MAPPING[level] }
    redarmy_artillery_turret['flags'] = { "placeable-player", "placeable-enemy" }
    redarmy_artillery_turret['max_health'] = ERM_UnitHelper.get_building_health(hitpoint, max_hitpoint_multiplier, level)
    redarmy_artillery_turret['healing_per_tick'] = ERM_UnitHelper.get_building_healing(hitpoint, max_hitpoint_multiplier, level)
    redarmy_artillery_turret['order'] = MOD_NAME .. '--building--' .. name .. '--'.. level
    redarmy_artillery_turret['minable'] = nil
    redarmy_artillery_turret['next_upgrade'] = nil
    redarmy_artillery_turret['resistances'] = {
        { type = "acid", percent = ERM_UnitHelper.get_resistance(base_acid_resistance, incremental_acid_resistance, level) },
        { type = "physical", percent = ERM_UnitHelper.get_resistance(base_physical_resistance, incremental_physical_resistance, level) },
        { type = "fire", percent = ERM_UnitHelper.get_resistance(base_fire_resistance, incremental_fire_resistance, level) },
        { type = "explosion", percent = ERM_UnitHelper.get_resistance(base_fire_resistance, incremental_fire_resistance, level) },
        { type = "laser", percent = ERM_UnitHelper.get_resistance(base_electric_resistance, incremental_electric_resistance, level) },
        { type = "electric", percent = ERM_UnitHelper.get_resistance(base_electric_resistance, incremental_electric_resistance, level) },
        { type = "cold", percent = ERM_UnitHelper.get_resistance(base_cold_resistance, incremental_cold_resistance, level) },
    }
    redarmy_artillery_turret['map_color'] = ERM_UnitHelper.format_map_color(settings.startup[FORCE_NAME.."-map-color"].value)
    redarmy_artillery_turret['rotation_speed'] = 0.001
    redarmy_artillery_turret['preparing_speed'] = 0.05
    redarmy_artillery_turret['folding_speed'] = 0.05
    redarmy_artillery_turret['automated_ammo_count'] = 5
    redarmy_artillery_turret['alert_when_attacking'] = false
    redarmy_artillery_turret['call_for_help_radius'] = 50
    redarmy_artillery_turret['spawn_decorations_on_expansion'] = false

    -- Attack Changes - Create custom gun for this level
    local gun_name = MOD_NAME .. '--' .. name .. '--gun--' .. level
    local cooldown = ERM_UnitHelper.get_attack_speed(base_attack_speed, incremental_attack_speed, level)
    local damage = ERM_UnitHelper.get_damage(base_physical_damage, incremental_physical_damage, level)

    local artillery_gun = util.table.deepcopy(data.raw['gun']['artillery-wagon-cannon'])
    artillery_gun.name = gun_name
    artillery_gun.attack_parameters.cooldown = cooldown
    artillery_gun.attack_parameters.range = attack_range
    artillery_gun.attack_parameters.min_range = 32
    artillery_gun.attack_parameters.damage_modifier = damage

    redarmy_artillery_turret['gun'] = gun_name

    data:extend({
        artillery_gun
    })

    redarmy_artillery_turret['corpse'] = MOD_NAME .. '--' .. name .. '--corpse'

    local redarmy_artillery_turret_corpse = util.table.deepcopy(data.raw['corpse']['artillery-turret-remnants'])
    redarmy_artillery_turret_corpse.name = MOD_NAME .. '--' .. name .. '--corpse'
    redarmy_artillery_turret_corpse.time_before_removed = minute * settings.startup["enemyracemanager-enemy-corpse-time"].value
    redarmy_artillery_turret_corpse.hidden = true
    redarmy_artillery_turret_corpse.hidden_in_factoriopedia  = true

    data:extend({
        redarmy_artillery_turret_corpse,
        redarmy_artillery_turret
    })
end