---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 4/23/2026 8:40 PM
---

local ERM_UnitHelper = require('__enemyracemanager__/lib/rig/unit_helper')
local GlobalConfig = require("__enemyracemanager__/lib/global_config")

function ErmRedArmy.make_boss_rocket_silo(level, boss_data)
    level = level or 1
    
    local rocket_silo = table.deepcopy(data.raw["rocket-silo"]["rocket-silo"])
    rocket_silo.name = MOD_NAME .. "--boss_rocket-silo--"..level
    rocket_silo.localised_name = { "entity-name." .. MOD_NAME .. "--boss_rocket-silo", GlobalConfig.QUALITY_MAPPING[level] }
    rocket_silo.minable.result = MOD_NAME .. "--boss_rocket-silo--"..level
    rocket_silo.max_health = boss_data.rocket_silo_hp[level]
    rocket_silo.subgroup = 'enemies'

    -- Remove power requirements
    rocket_silo.energy_source = {
        type = "void"
    }
    rocket_silo.energy_usage = "1kW"
    rocket_silo.lamp_energy_usage = "0kW"
    rocket_silo.active_energy_usage = "1kW"
    rocket_silo.rocket_parts_required = 100

    rocket_silo.dying_trigger_effect = {
        {
            type = "script",
            effect_id = TRIGGER_BOSS_DIES,
        }
    }
    rocket_silo.created_effect = {
        type = "direct",
        action_delivery = {
            type = "instant",
            source_effects = {
                {
                    type = "script",
                    effect_id = TRIGGER_BOSS_SPAWNED
                }
            }
        }
    }

    data:extend({
        rocket_silo
    })

    -- Create the item for the new rocket silo
    local rocket_silo_item = table.deepcopy(data.raw.item["rocket-silo"])
    rocket_silo_item.name = MOD_NAME.."--boss_rocket-silo--"..level
    rocket_silo_item.place_result = MOD_NAME.."--boss_rocket-silo--"..level
    rocket_silo_item.subgroup = 'enemies'

    data:extend({rocket_silo_item})
end