---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 4/4/2026 1:38 PM
---
local ERM_UnitHelper = require('__enemyracemanager__/lib/rig/unit_helper')
local rocket_silo = table.deepcopy(data.raw["rocket-silo"]["rocket-silo"])

rocket_silo.name = MOD_NAME.."--rocket-silo--5"
rocket_silo.minable.result = MOD_NAME.."--rocket-silo--5"
rocket_silo.max_health = ERM_UnitHelper.get_health(
    rocket_silo.max_health * 10 , 
    settings.startup["enemyracemanager-max-hitpoint-multipliers"].value, 
    5
) 

-- Remove power requirements
rocket_silo.energy_source = {
  type = "void"
}
rocket_silo.energy_usage = "1kW"
rocket_silo.lamp_energy_usage = "0kW"
rocket_silo.active_energy_usage = "1kW"
rocket_silo.rocket_parts_required = 100

data:extend({
  rocket_silo
})

-- Create the item for the new rocket silo
local rocket_silo_item = table.deepcopy(data.raw.item["rocket-silo"])
rocket_silo_item.name = MOD_NAME.."--rocket-silo--5"
rocket_silo_item.place_result = MOD_NAME.."--rocket-silo--5"

data:extend({rocket_silo_item})