---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/28/2021 9:38 PM
---

require('util')

local ERM_UnitHelper = require('__enemyracemanager__/lib/rig/unit_helper')
local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
local ERM_DebugHelper = require('__enemyracemanager__/lib/debug_helper')
local GlobalConfig = require('__enemyracemanager__/lib/global_config')

local enemy_autoplace = require("__enemyracemanager__/prototypes/enemy-autoplace")

local name = 'tesla-turret'

-- Hitpoints
local hitpoint = 600
local max_hitpoint_multiplier = settings.startup["enemyracemanager-max-hitpoint-multipliers"].value * 1.5

-- Resistance values
local base_acid_resistance = 10
local incremental_acid_resistance = 65
local base_physical_resistance = 0
local incremental_physical_resistance = 75
local base_fire_resistance = 0
local incremental_fire_resistance = 75
local base_electric_resistance = 20
local incremental_electric_resistance = 70
local base_cold_resistance = 10
local incremental_cold_resistance = 65

-- Damage values
local base_electric_damage = 0.5
local incremental_electric_damage = 1.5

-- Attack Speed
local base_attack_speed = 180
local incremental_attack_speed = 60

local collision_box = { { -2, -2 }, { 2, 2} }
local map_generator_bounding_box = { { -4, -4 }, { 4, 4} }
local selection_box = { { -2, -2 }, { 2, 2} }

function ErmRedArmy.make_tesla_turret(level)
    level = level or 1

    local attack_range = ERM_UnitHelper.get_attack_range(level) + 20

    local redarmy_tesla_turret = util.table.deepcopy(data.raw['electric-turret']['tesla-turret'])

    -- Base changes
    redarmy_tesla_turret['type'] = 'turret'
    redarmy_tesla_turret['subgroup'] = 'enemies'
    redarmy_tesla_turret['name'] = MOD_NAME .. '--' .. name .. '--' .. level
    redarmy_tesla_turret['localised_name'] = { 'entity-name.' .. MOD_NAME .. '--' .. name, GlobalConfig.QUALITY_MAPPING[level] }
    redarmy_tesla_turret['flags'] = { "placeable-player", "placeable-enemy" }
    redarmy_tesla_turret['max_health'] = ERM_UnitHelper.get_building_health(hitpoint, max_hitpoint_multiplier, level)
    redarmy_tesla_turret['healing_per_tick'] = ERM_UnitHelper.get_building_healing(hitpoint, max_hitpoint_multiplier, level)
    redarmy_tesla_turret['order'] = MOD_NAME .. '--building--' .. name .. '--'.. level
    redarmy_tesla_turret['minable'] = nil
    redarmy_tesla_turret['next_upgrade'] = nil
    redarmy_tesla_turret['collision_mask'] = nil
    redarmy_tesla_turret['resistances'] = {
        { type = "acid", percent = ERM_UnitHelper.get_resistance(base_acid_resistance, incremental_acid_resistance, level) },
        { type = "poison", percent = ERM_UnitHelper.get_resistance(base_acid_resistance, incremental_acid_resistance, level) },
        { type = "physical", percent = ERM_UnitHelper.get_resistance(base_physical_resistance, incremental_physical_resistance, level) },
        { type = "fire", percent = ERM_UnitHelper.get_resistance(base_fire_resistance, incremental_fire_resistance, level) },
        { type = "explosion", percent = ERM_UnitHelper.get_resistance(base_fire_resistance, incremental_fire_resistance, level) },
        { type = "laser", percent = ERM_UnitHelper.get_resistance(base_electric_resistance, incremental_electric_resistance, level) },
        { type = "electric", percent = ERM_UnitHelper.get_resistance(base_electric_resistance, incremental_electric_resistance, level) },
        { type = "cold", percent = ERM_UnitHelper.get_resistance(base_cold_resistance, incremental_cold_resistance, level) }
    }
    redarmy_tesla_turret['map_color'] = ERM_UnitHelper.format_map_color(settings.startup[FORCE_NAME.."-map-color"].value)
    redarmy_tesla_turret['collision_box'] = collision_box
    redarmy_tesla_turret['selection_box'] = selection_box
    redarmy_tesla_turret['map_generator_bounding_box'] = map_generator_bounding_box
    redarmy_tesla_turret['autoplace'] = enemy_autoplace.enemy_worm_autoplace({
        probability_expression = "erm_redarmy_autoplace_base(0, 8)",
        force = FORCE_NAME,
        control = AUTOCONTROL_NAME
    })
    redarmy_tesla_turret['call_for_help_radius'] = 50
    redarmy_tesla_turret['spawn_decorations_on_expansion'] = false
    redarmy_tesla_turret['energy_source'] = nil

    -- Attack Changes
    redarmy_tesla_turret['attack_parameters'] =
    {
        type = "beam",
        cooldown = ERM_UnitHelper.get_attack_speed(base_attack_speed, incremental_attack_speed, level),
        cooldown_deviation = 0.1,
        range = attack_range,
        damage_modifier = ERM_UnitHelper.get_damage(base_electric_damage, incremental_electric_damage, level), 
        range_mode = "center-to-bounding-box",
        fire_penalty = 0.9,
        source_direction_count = 64,
        source_offset = {0, -0.55},
        ammo_category = "redarmy-damage",
        ammo_type =
        {
            category = "redarmy-damage",
            action =
            {
                type = "direct",
                action_delivery =
                {
                    type = "instant",
                    target_effects =
                    {
                        -- Chain effect must go first in case the beam kills the target
                        {
                            type = "nested-result",
                            action =
                            {
                                type = "direct",
                                action_delivery =
                                {
                                    type = "chain",
                                    chain = "chain-tesla-turret-chain",
                                }
                            }
                        },
                        {
                            type = "nested-result",
                            action =
                            {
                                type = "direct",
                                action_delivery =
                                {
                                    type = "beam",
                                    beam = "chain-tesla-turret-beam-start",
                                    max_length = 40,
                                    duration = 30,
                                    add_to_shooter = false,
                                    destroy_with_source_or_target = false,
                                    source_offset = {0, -2.6}
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    redarmy_tesla_turret['corpse'] = MOD_NAME .. '--' .. name .. '--corpse'

    -- Animation Changes
    ERM_UnitTint.mask_tint(redarmy_tesla_turret['folded_animation']['layers'][3], ERM_UnitTint.tint_red())
    ERM_UnitTint.mask_tint(redarmy_tesla_turret['preparing_animation']['layers'][3], ERM_UnitTint.tint_red())
    ERM_UnitTint.mask_tint(redarmy_tesla_turret['prepared_animation']['layers'][3], ERM_UnitTint.tint_red())
    ERM_UnitTint.mask_tint(redarmy_tesla_turret['folding_animation']['layers'][2], ERM_UnitTint.tint_red())

    local redarmy_tesla_turret_corpse = util.table.deepcopy(data.raw['corpse']['tesla-turret-remnants'])
    redarmy_tesla_turret_corpse.name = MOD_NAME .. '--' .. name .. '--corpse'
    redarmy_tesla_turret_corpse.time_before_removed = minute * settings.startup["enemyracemanager-enemy-corpse-time"].value
    redarmy_tesla_turret_corpse.hidden = true
    redarmy_tesla_turret_corpse.hidden_in_factoriopedia  = true

    data:extend({
        redarmy_tesla_turret_corpse,
        redarmy_tesla_turret
    })
end