---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 4/12/2026 11:52 PM
---

local Artillery = {}

function Artillery.register(artillery_turret)
    if artillery_turret then
        local prototype = artillery_turret.prototype
        storage.active_artilleries[artillery_turret.unit_number] = {
            entity = artillery_turret,
            manual_range_modifier = prototype.manual_range_modifier,
            turret_range = prototype.attack_parameters.range
        }
        return true
    end
    return false
end

function Artillery.add_ammo(event)
    local active_artilleries = storage.active_artilleries
    for unit_number, data in pairs(active_artilleries) do
        if data and data.entity.valid then
            local active_artillery = data.entity
            if active_artillery then
                local ammo_inventory = active_artillery.get_inventory(defines.inventory.artillery_turret_ammo)
                local shell = {name="artillery-shell", count = 6}
                if ammo_inventory and ammo_inventory.can_insert(shell) then
                    ammo_inventory.insert(shell)
                end
            end
        else
            active_artilleries[unit_number] = nil
        end
    end
end

local is_valid_artillery = function(event)
    local entity = event.created_entity or event.entity
    if entity and entity.valid and entity.type == "artillery-turret" and entity.force.name == FORCE_NAME then
        return true
    end
    return false
end

Artillery.on_nth_tick = {
    [minute] = Artillery.add_ammo
}

Artillery.events = {
    [defines.events.script_raised_built] =  function(event)
        if is_valid_artillery(event) then
            local artillery = event.created_entity or event.entity
            Artillery.register(artillery)
        end
    end
}

return Artillery