---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/28/2022 8:19 PM
---
local BossAttackRemote = require("__enemyracemanager__/lib/boss_attack_data")
local BossAttackProcessor = require("__enemyracemanager__/lib/boss_attack_processor")

---
---
--- Boss perform attacks when it take around the following damage numbers
---
--- @see __enemyracemanager__/lib/boss_attack_data.lua for full data structure
---
BossAttackRemote.basic_attacks =
{
    attack_name = {"explosive-rocket-he", "explosive-rocket-8", "explosive-rocket-4"},
    attack_type = {
        BossAttackProcessor.TYPE_PROJECTILE,
        BossAttackProcessor.TYPE_PROJECTILE,
        BossAttackProcessor.TYPE_PROJECTILE,
    },
    attack_chance = {
        --- Final attack always roll 100%, but up to the dev. 
        {20, 20, 20, 20, 20},
        {50, 50, 50, 50, 50},
        {100, 100, 100, 100, 100}
    },
    attack_count = {1, 2, 3},
    attack_spread = {1, 1, 1},
    attack_use_multiplier = {true, true, true},
    attack_count_multiplier = {
        {1, 1, 1, 2, 2},
        {1, 1, 2, 2, 2},
        {1, 1, 2, 2, 3}
    },
    attack_spread_multiplier = {
        {1, 1, 1, 2, 2},
        {1, 1, 2, 2, 2},
        {1, 1, 2, 2, 3}
    },
}

---
--- heavy_attacks, all spawning attacks
---
BossAttackRemote.heavy_attacks =
{
    attack_name = {"plane-bomber","tank-explosive-cannon","tank-cannon","human-sniper","human-shotgun"},
    attack_type = {
        BossAttackProcessor.TYPE_UNIT_SPAWN,
        BossAttackProcessor.TYPE_UNIT_SPAWN,
        BossAttackProcessor.TYPE_UNIT_SPAWN,
        BossAttackProcessor.TYPE_UNIT_SPAWN,
        BossAttackProcessor.TYPE_UNIT_SPAWN,
    },
    attack_chance = {
        {10, 15, 20, 20, 20},
        {25, 25, 25, 25, 25},
        {25, 25, 25, 25, 25},
        {50, 50, 50, 50, 50},
        {100, 100, 100, 100, 100},
    },
    attack_count = {6, 6, 8, 12, 12},
    attack_spread = {1, 1, 1, 1, 1},
    attack_use_multiplier = {false, false, false, false, false},
    attack_count_multiplier = {
        {},
    },
    attack_spread_multiplier = {
        {},
    },
}

---
--- assist_attacks
---
BossAttackRemote.assist_attacks =
{
    attack_name = {'artillery-turret', 'boss_lab'},
    attack_type = {
        BossAttackProcessor.TYPE_STRUCT_SPAWN,
        BossAttackProcessor.TYPE_STRUCT_SPAWN,
    },
    attack_chance = {
        {50,50,50,50,50},
        {100,100,100,100,100},
    },
    max_structure_count = {
        {5,5,6,8,10},
        --- Boss assist spawner uses a separated max count
        {99,99,99,99,99},
    },
    attack_count = {1, 1},
    attack_spread = {1, 1},
    attack_use_multiplier = {false, false},
    attack_count_multiplier = {
        {},
    },
    attack_spread_multiplier = {
        {},
    },
}

---
--- special_attacks, only target player radar, Falling projectile bypasses defenses.
---
BossAttackRemote.special_attacks =
{
    attack_name = {"explosive-rocket-he","increase_attack_point_2x","explosive-rocket-he"},
    attack_type = {
        BossAttackProcessor.TYPE_FALLING_PROJECTILE,
        BossAttackProcessor.TYPE_INCREASE_ATTACK_POINT,
        BossAttackProcessor.TYPE_FALLING_PROJECTILE
    },
    attack_chance = {
        {20, 20, 20, 20, 20},
        {50, 50, 50, 50, 50},
        {100,100,100,100,100},
    },
    attack_count = {2, 2, 3},
    attack_spread = {3, 1, 5},
    attack_use_multiplier = {false, false, false},
    only_targets_radar = {true, false, false},
    can_aim_attackable_targets = {false, false, true},
    unique_position = {false, false, true},
    attack_count_multiplier = {},
    attack_spread_multiplier = {},
}

BossAttackRemote.ultimate_attacks =
{
    attack_name = {"atomic-rocket", "atomic-rocket", "atomic-rocket"},
    attack_type = {
        BossAttackProcessor.TYPE_FALLING_PROJECTILE,
        BossAttackProcessor.TYPE_FALLING_PROJECTILE,
        BossAttackProcessor.TYPE_FALLING_PROJECTILE,
    },
    attack_chance = {
        {20,20,20,20,20},
        {33,33,33,33,33},
        {100,100,100,100,100},
    },
    only_targets_radar = {true, false, false},
    can_aim_attackable_targets = {false, true, true},
    attack_count = {1, 1, 1},
    attack_spread = {1, 4, 2},
    attack_use_multiplier = {false, false, false},
    unique_position = {false, true, true},
    attack_count_multiplier = {
        {},
    },
    attack_spread_multiplier = {
        {},
    },
}

BossAttackRemote.despawn_attacks =
{
    attack_name = {"increase_attack_point_20x"},
    attack_type = {
        BossAttackProcessor.TYPE_INCREASE_ATTACK_POINT,
    },
    attack_chance = {
        {100,100,100,100,100}
    },
    select_nearby_enemy_count = {1},
    attack_count = {20},
    attack_spread = {1},
    attack_use_multiplier = {false},
    attack_count_multiplier = {
        {},
    },
    attack_spread_multiplier = {
        {},
    },
}

BossAttackRemote.idle_attacks =
{
    attack_name = {"explosive-rocket-he","plane-dropship", "select_unit_1x", "explosive-rocket-8"},
    attack_type = {
        BossAttackProcessor.TYPE_FALLING_PROJECTILE,
        BossAttackProcessor.TYPE_UNIT_SPAWN,
        BossAttackProcessor.TYPE_SELECT_NEARBY_ENEMY,
        BossAttackProcessor.TYPE_FALLING_PROJECTILE,
    },
    attack_chance = {
        {25,25,25,25,25},
        {25,25,25,25,25},
        {50,50,50,50,50},
        {100,100,100,100,100},
    },
    attack_count = {1, 20, 1, 1},
    attack_spread = {2, 1, 1, 4},
    only_targets_radar = {true, false, true, true},
    can_aim_attackable_targets = {false, true, false,false},
    select_nearby_enemy_count = {1,1,1,1,1},
    attack_use_multiplier = {false, false, false, false,false},
    attack_count_multiplier = {
        {},
    },
    attack_spread_multiplier = {
        {},
    },
}

return BossAttackRemote