---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 4/16/2026 11:46 PM
---
local ForceHelper = require('__enemyracemanager__/lib/helper/force_helper')
local CustomAttacks = require('__erm_redarmy__/scripts/custom_attacks')
local EmotionConstants = require('__enemyracemanager__/lib/emotion_constants')
require('__erm_redarmy__/global')


local createRace = function()
    local force = game.forces[FORCE_NAME]
    if not force then
        force = game.create_force(FORCE_NAME)
    end

    force.ai_controllable = true;
    force.disable_research()
    force.friendly_fire = false;

    if settings.startup['enemyracemanager-free-for-all'].value then
        ForceHelper.set_friends(game, FORCE_NAME, false)
    else
        ForceHelper.set_friends(game, FORCE_NAME, true)
    end

    ForceHelper.set_neutral_force(game, FORCE_NAME)

    --- for guerrilla tactic processing
    storage.guerrilla_distances = storage.guerrilla_distances or {}

    storage.building_entities = storage.building_entities or {}
    storage.landfill_queue = storage.landfill_queue or {}
    storage.base_area_removal = storage.base_area_removal or {}

    --- Attack job fires once per second, for nuclear silos and artilleries manual target.
    storage.attack_jobs = storage.attack_jobs or {}

    storage.active_artilleries = storage.active_artilleries or {}
    storage.active_nuclear_silos = storage.active_nuclear_silos or {}
end

local addRaceSettings = function()
    local race_settings = remote.call('enemyracemanager', 'get_race', MOD_NAME)
    if race_settings == nil then
        race_settings = {}
    end

    race_settings.race = race_settings.race or MOD_NAME
    race_settings.label = { 'gui.label-erm_redarmy' }
    race_settings.tier = race_settings.tier or 1
    race_settings.is_primitive = race_settings.is_primitive or false
    race_settings.autoplace_name = race_settings.autoplace_name or AUTOCONTROL_NAME
    race_settings.attack_meter = race_settings.attack_meter or 0
    race_settings.attack_meter_total = race_settings.attack_meter_total or 0
    race_settings.last_attack_meter_total = race_settings.last_attack_meter_total or 0
    race_settings.next_attack_threshold = race_settings.next_attack_threshold or 0

    race_settings.units = {
        { 'human-miner', 'human-pistol', 'human-machinegun' },
        { 'human-sniper', 'tank-cannon', 'plane-dropship', 'human-engineer' },
        { 'human-flamethrower', 'human-shotgun', 'tank-explosive-cannon', 'plane-gunner', 'plane-bomber' },
    }
    race_settings.turrets = {
        { 'gun-turret', 'laser-turret' },
        { 'rocket-turret' },
        { 'tesla-turret' },
    }
    race_settings.command_centers = {
        { 'lab' },
        {},
        {}
    }
    race_settings.support_structures = {
        { 'assemble-machine' },
        { 'electric-furnace' },
        { },
    }
    race_settings.timed_units = {
    }
    race_settings.flying_units = {
        { 'plane-gunner' },
        { 'plane-dropship' },
        { 'plane-bomber' }
    }
    race_settings.builder = 'human-engineer'
    race_settings.dropship = 'plane-dropship'
    race_settings.droppable_units = {
        { { 'human-miner', 'human-pistol' }, { 3, 1 } },
        { { 'human-machinegun', 'tank-cannon' }, { 4, 2 } },
        { { 'human-flamethrower', 'human-shotgun', 'tank-cannon', 'tank-explosive-cannon' }, { 4, 2, 1, 1 } },
    }
    race_settings.construction_buildings = {
        { { 'gun-turret-short' }, { 1 } },
        { { 'gun-turret-short' }, { 1 } },
        { { 'gun-turret-short', 'lab' }, { 2, 1 } },
    }
    race_settings.featured_groups = {
        -- Unit list, spawn ratio, unit attack point cost
        { { 'human-flamethrower', 'human-shotgun', 'human-sniper', 'human-engineer', 'plane-bomber' }, { 1, 2, 2, 1, 1 }, 20 },
        { { 'human-machinegun', 'human-flamethrower', 'human-sniper', 'tank-explosive-cannon' }, { 2, 1, 1, 1 }, 25 },
        { { 'tank-cannon', 'tank-explosive-cannon' }, { 2, 1 }, 35 },
        { { 'human-shotgun', 'tank-cannon', 'tank-explosive-cannon', 'human-flamethrower', 'plane-bomber' }, { 2, 2, 1, 2, 1 }, 25 },
        { { 'human-sniper', 'tank-cannon', 'tank-explosive-cannon', 'human-flamethrower', 'plane-bomber' }, { 2, 2, 1, 2, 1 }, 25 },
        { { 'human-shotgun', 'human-sniper', 'tank-cannon', 'tank-explosive-cannon', 'plane-gunner', 'plane-bomber' }, {2, 1, 2, 2, 1, 1 }, 25 },
        { { 'human-shotgun', 'human-sniper', 'human-flamethrower', 'tank-cannon', 'tank-explosive-cannon', 'plane-bomber' }, {2, 1, 2, 1, 1, 1 }, 25 },
    }
    race_settings.featured_flying_groups = {
        { { 'plane-gunner', 'plane-bomber' }, { 3, 1 }, 75 },
        { { 'plane-gunner', 'plane-dropship' }, { 3, 1 }, 100 },
        { { 'plane-gunner', 'plane-bomber','plane-dropship' }, { 3, 2, 1}, 75 },
    }
    race_settings.home_planet = "earth"
    race_settings.interplanetary_attack_active = race_settings.interplanetary_attack_active or false


    race_settings.boss_custom_spawn = true
    race_settings.boss_building = "boss_rocket_silo"
    race_settings.boss_assisted_spawner = "boss_lab"
    race_settings.pathing_unit = "human-miner"
    race_settings.colliding_unit = "tank-cannon"
    race_settings.boss_tier = race_settings.boss_tier or 1
    race_settings.boss_kill_count = race_settings.boss_kill_count or 0

    race_settings.structure_killed_count_by_planet = race_settings.structure_killed_count_by_planet or {}
    race_settings.unit_killed_count_by_planet = race_settings.unit_killed_count_by_planet or {}

    --- Arrange it from lowest chance to highest chance, as it starts from first item
    race_settings.emotion_data = {
        -- emotion_type, spawn_chance, compare as dark/light, darkness_value (0-1),cooldown_interval, group_size_multiplier
        {EmotionConstants.EMO_RAPID_EXPAND, 10, EmotionConstants.DARK, 0.65, 2 * minute, 0.2},
        {EmotionConstants.EMO_RUSH, 10, EmotionConstants.LIGHT, 0.5, 30 * second, 0.33},
        {EmotionConstants.EMO_DOUBLE_TAP, 15, EmotionConstants.LIGHT, 0.65, 5 * minute, 0.8},
        {EmotionConstants.EMO_SIEGE, 20, EmotionConstants.LIGHT, 0.5, 3 * minute, 1},
    }

    race_settings.boss_emotion_data = {
        -- emotion_type, spawn_chance, compare as dark/light, darkness_value (0-1),cooldown_interval, group_size_multiplier
        {EmotionConstants.EMO_RUSH, 33, EmotionConstants.ALL_DAY, 0, 15 * second, 0.5},
        {EmotionConstants.EMO_DOUBLE_TAP, 66, EmotionConstants.ALL_DAY, 0, 2 * minute, 1},
        {EmotionConstants.EMO_SIEGE, 100, EmotionConstants.ALL_DAY, 0, 2 * minute, 1.2},
    }
    
    for _, item in pairs(prototypes.mod_data) do
        if item.data_type == MOD_NAME..'.boss_data' then
            race_settings.boss_settings = {}
            race_settings.boss_settings = item.data
        end
    end
    
    remote.call('enemyracemanager', 'register_race', race_settings)

    CustomAttacks.get_race_settings(MOD_NAME, true)
end

local on_init = function(event)
    createRace()
    addRaceSettings()
end

local on_configuration_changed = function(event)
    createRace()
    addRaceSettings()
end

local attack_functions = {
    [DROPSHIP_ATTACK] = function(args)
        CustomAttacks.process_dropship(args)
    end,
    [ENGINEER_ATTACK] = function(args)
        CustomAttacks.process_engineer(args)
    end,
    [GUERRILLA_ATTACK] = function(args)
        CustomAttacks.process_guerrilla(args)
    end
}

local on_script_trigger_effect =  function(event)
    if attack_functions[event.effect_id] and
            CustomAttacks.valid(event, MOD_NAME)
    then
        attack_functions[event.effect_id](event)
    end
end


local InitController = {}

InitController.events = {
    [defines.events.on_script_trigger_effect] = on_script_trigger_effect
}

InitController.on_configuration_changed = on_configuration_changed

InitController.on_init = on_init

return InitController