---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 4/12/2026 10:11 PM
---

local NuclearSilo = {}

local draw_text = rendering.draw_text
local notification_enabled = settings.startup[FORCE_NAME.."-orbital-surveillance"].value

function NuclearSilo.register(silo)
    if silo then
        silo.send_to_orbit_automatically = true

        -- Add to active silos table
        table.insert(storage.active_nuclear_silos, {
            entity = silo,
        })
        
        return true
    end
    
    return false
end

function NuclearSilo.spawn_nuclear_rocket(surface, launch_position, target_position)
    -- Create the nuclear rocket projectile
    local nuclear_rocket = surface.create_entity({
        name = "atomic-rocket",
        position = launch_position,
        target = target_position,
        speed = 3
    })

    return nuclear_rocket
end

function NuclearSilo.launch_rocket_from_silo(silo)
    if not silo or not silo.valid then
        return false
    end
    
    local launched = silo.launch_rocket()
    
    if launched and notification_enabled then
        draw_text({
            text = "[item=atomic-bomb]",
            color = {r = 1, g = 1, b = 1},
            scale = 2,
            target = silo.position,
            surface = silo.surface,
            render_mode = "chart",
            use_rich_text = true,
            time_to_live = 120 * second,
            scale_with_zoom = true,
            blink_interval = 30,
        })
    end
    
    return launched
end

function NuclearSilo.add_parts(event)
    local active_silos = storage.active_nuclear_silos
    
    for index, active_silo_data in pairs(active_silos) do
        local active_silo = active_silo_data.entity
        if active_silo.valid then
            NuclearSilo.launch_rocket_from_silo(active_silo)
            active_silo.rocket_parts = active_silo.rocket_parts + 10
        else
            table.remove(storage.active_nuclear_silos, index)
        end
    end
end

local is_valid_silo = function(event)
    local entity = event.created_entity or event.entity
    if entity and entity.valid and entity.type == 'rocket-silo' and entity.force.name == FORCE_NAME then
        return true
    end
    return false
end

local refuel = settings.startup[FORCE_NAME.."-atomic-rocket-refuel"].value
NuclearSilo.on_nth_tick = {
    [refuel * minute + 1] = NuclearSilo.add_parts
}


NuclearSilo.events = {
    [defines.events.script_raised_built] =  function(event)
        if is_valid_silo(event) then
            local silo = event.created_entity or event.entity
            NuclearSilo.register(silo)
        end
    end,
    [defines.events.on_rocket_launched] = function(event)
        local rocket = event.rocket
        if is_valid_silo({ created_entity = event.rocket_silo  }) then
            NuclearSilo.spawn_nuclear_rocket(rocket.surface, rocket.position, { x=100,y=100 })
        end
    end
}

local init = function(event)
    storage.active_nuclear_silos = storage.active_nuclear_silos or {}
end

NuclearSilo.on_configuration_changed = init

NuclearSilo.on_init = init

return NuclearSilo