---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 4/12/2026 10:11 PM
---

local NuclearSilo = {}

function NuclearSilo.register(silo)
    if silo then
        silo.send_to_orbit_automatically = true

        -- Add to active silos table
        table.insert(storage.active_nuclear_silos, {
            entity = silo,
            charted = false,
        })
        
        return true
    end
    
    return false
end

function NuclearSilo.spawn_nuclear_rocket(surface, launch_position, target_position)
    -- Create the nuclear rocket projectile
    local nuclear_rocket = surface.create_entity({
        name = "atomic-rocket",
        position = launch_position,
        target = target_position,
        speed = 1
    })

    return nuclear_rocket
end

function NuclearSilo.launch_rocket_from_silo(silo)
    if not silo or not silo.valid then
        return false
    end
    
    return silo.launch_rocket()
end

function NuclearSilo.add_parts(event)
    local active_silos = storage.active_nuclear_silos
    local player_forces = remote.call('enemyracemanager', 'get_player_forces')
    
    for index, active_silo_data in pairs(active_silos) do
        local active_silo = active_silo_data.entity
        if active_silo.valid then
            if active_silo_data.is_charted then
                NuclearSilo.launch_rocket_from_silo(active_silo)
                active_silo.rocket_parts = active_silo.rocket_parts + 10
            else
                for _, player_force in pairs(player_forces) do
                    local force = game.forces[player_force]
                    if force and force.is_chunk_charted(active_silo.surface,
                            {
                                x = math.floor(active_silo.position.x / 32),
                                y = math.floor(active_silo.position.y / 32)
                            }
                    ) then
                        storage.active_nuclear_silos[index].is_charted = true
                    end
                end
            end
        else
            table.remove(storage.active_nuclear_silos, index)
        end
    end
end

local is_valid_silo = function(event)
    local entity = event.created_entity or event.entity
    if entity and entity.valid and entity.type == 'rocket-silo' and entity.force.name == FORCE_NAME then
        return true
    end
    return false
end

NuclearSilo.on_nth_tick = {
    [5 * minute] = NuclearSilo.add_parts
}


NuclearSilo.events = {
    [defines.events.script_raised_built] =  function(event)
        if is_valid_silo(event) then
            local silo = event.created_entity or event.entity
            NuclearSilo.register(silo)
        end
    end,
    [defines.events.on_rocket_launched] = function(event)
        local rocket = event.rocket
        if is_valid_silo({ created_entity = event.rocket_silo  }) then
            NuclearSilo.spawn_nuclear_rocket(rocket.surface, rocket.position, { x=100,y=100 })
        end
    end
}

return NuclearSilo