---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/8/2023 9:02 PM
---
local ErmConfig = require('__enemyracemanager__/lib/global_config')
local CustomAttacks = require('scripts/custom_attacks')
local Position = require("__erm_libs__/stdlib/position")

local RemoteAPI = {}

function RemoteAPI.milestones_preset_addons()
    local boss_level = ErmConfig.BOSS_LEVELS
    local preset = {
        ["erm_redarmy"] = {
            required_mods = { "erm_redarmy" },
            milestones = {
                { type = "group", name = "Kills" },
                { type = "kill", name = "erm_redarmy/lab/5", quantity = 1 },
                { type = "kill", name = "erm_redarmy/lab/10", quantity = 1 },
                { type = "kill", name = "erm_redarmy/lab/15", quantity = 1 },
                { type = "kill", name = "erm_redarmy/lab/20", quantity = 1, next = "x10" },
            }
        },
    }

    --preset["erm_redarmy_boss"] = {
    --    required_mods = {"erm_redarmy"},
    --    milestones = {
    --        {type="group", name="ERM Boss Kills"},
    --        {type="kill", name="erm_redarmy/warpgate/"..boss_level[1],  quantity=1},
    --        {type="kill", name="erm_redarmy/warpgate/"..boss_level[2],  quantity=1},
    --        {type="kill", name="erm_redarmy/warpgate/"..boss_level[3],  quantity=1},
    --        {type="kill", name="erm_redarmy/warpgate/"..boss_level[4],  quantity=1},
    --        {type="kill", name="erm_redarmy/warpgate/"..boss_level[5],  quantity=1},
    --    }
    --}

    return preset
end

---
--- Print global for debug purpose when you run remote.call("enemyracemanager_debug", "print_global")"
---
function RemoteAPI.print_global()
    helpers.write_file("erm_redarmy/erm-global.json", helpers.table_to_json(util.copy(storage)))
end

function RemoteAPI.register_new_enemy_race()
    return MOD_NAME
end

function RemoteAPI.refresh_custom_attack_cache()
    CustomAttacks.get_race_settings(MOD_NAME, true)
end

--- Add home planet to ignore list
function RemoteAPI.interplanetary_attack_ignore_planets()
    return {'earth'}
end

function RemoteAPI.register_ignore_planet_for_indestructible_entity()
    return {'earth'}
end

function RemoteAPI.advanced_target_priorities_register_section_data()
    local data =  {
        {
            delimiter = '--',
            name = "erm_redarmy",
            prefix = 'enemy_erm_redarmy',
            suffix = nil,
            --- 4 type of options 'size', 'unit_type', 'tier','variant'
            options = {
                { 'human-miner', 'human-pistol', 
                  'human-machinegun', 'human-sniper',
                  'human-flamethrower', 'human-shotgun',
                  'tank-cannon',  'tank-explosive-cannon',
                  'plane-dropship', 'human-engineer',
                  'plane-gunner', 'plane-bomber' 
                },
                {1,2,3,4,5}
            },
            unit_type_columns = 2,
            --- controls order of text concatenation
            option_titles = {
                'unit_type', 'tier'
            },
            option_delimiters = {
            }
        }
    }

    return data
end

--- grab nearest nuclear silo, turn it into boss.
--- return true or message for reject
function RemoteAPI.boss_custom_spawn(radar, is_test)
    if not radar and not radar.valid then
        return {"","boss_radar.radar_invalid"}
    end
    
    local surface = radar.surface
    local silos = surface.find_entities_filtered { name = MOD_NAME .. '--rocket-silo--5'}
    local valid_silo = nil
    for _, silo in pairs(silos) do
        local player_spawn = silo.force.get_spawn_position(surface) or {0, 0}
        if Position.distance(silo.position, player_spawn) > 512 or is_test == true then
            game.print('pass boss_custom_spawn')
            valid_silo = silo
            break
        end
    end

    if not valid_silo then
        return {"", "boss_radar.rocket_silo_too_close_to_radar"}
    end
    
    local position = valid_silo.position
    valid_silo.destroy()

    CustomAttacks.get_race_settings(FORCE_NAME, game.forces[FORCE_NAME])
    local boss_silo = surface.create_entity {
        name = MOD_NAME .. '--boss_rocket-silo--' .. storage.custom_attack_race_settings[FORCE_NAME].boss_tier,
        position = position,
        force = FORCE_NAME,
        raise_built = true
    }
    return boss_silo
end

return RemoteAPI
