---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/8/2023 9:02 PM
---
local ErmConfig = require('__enemyracemanager__/lib/global_config')
local CustomAttacks = require('scripts/custom_attacks')

local RemoteAPI = {}

function RemoteAPI.milestones_preset_addons()
    local boss_level = ErmConfig.BOSS_LEVELS
    local preset = {
        ["erm_redarmy"] = {
            required_mods = { "erm_redarmy" },
            milestones = {
                { type = "group", name = "Kills" },
                { type = "kill", name = "erm_redarmy/lab/5", quantity = 1 },
                { type = "kill", name = "erm_redarmy/lab/10", quantity = 1 },
                { type = "kill", name = "erm_redarmy/lab/15", quantity = 1 },
                { type = "kill", name = "erm_redarmy/lab/20", quantity = 1, next = "x10" },
            }
        },
    }

    --preset["erm_redarmy_boss"] = {
    --    required_mods = {"erm_redarmy"},
    --    milestones = {
    --        {type="group", name="ERM Boss Kills"},
    --        {type="kill", name="erm_redarmy/warpgate/"..boss_level[1],  quantity=1},
    --        {type="kill", name="erm_redarmy/warpgate/"..boss_level[2],  quantity=1},
    --        {type="kill", name="erm_redarmy/warpgate/"..boss_level[3],  quantity=1},
    --        {type="kill", name="erm_redarmy/warpgate/"..boss_level[4],  quantity=1},
    --        {type="kill", name="erm_redarmy/warpgate/"..boss_level[5],  quantity=1},
    --    }
    --}

    return preset
end

function RemoteAPI.register_new_enemy_race()
    return MOD_NAME
end

function RemoteAPI.refresh_custom_attack_cache()
    CustomAttacks.get_race_settings(MOD_NAME, true)
end

--- Add home planet to ignore list
function RemoteAPI.interplanetary_attack_ignore_planets()
    return {'earth'}
end

function RemoteAPI.advanced_target_priorities_register_section_data()
    local data =  {
        {
            delimiter = '--',
            name = "erm_redarmy",
            prefix = 'enemy_erm_redarmy',
            suffix = nil,
            --- 4 type of options 'size', 'unit_type', 'tier','variant'
            options = {
                { 'human-miner', 'human-pistol', 
                  'human-machinegun', 'human-sniper',
                  'human-flamethrower', 'human-shotgun',
                  'tank-cannon',  'tank-explosive-cannon',
                  'plane-dropship', 'human-engineer',
                  'plane-gunner', 'plane-bomber' 
                },
                {1,2,3,4,5}
            },
            unit_type_columns = 2,
            --- controls order of text concatenation
            option_titles = {
                'unit_type', 'tier'
            },
            option_delimiters = {
            }
        }
    }

    return data
end

return RemoteAPI
